---
- include_tasks: single-deploy.yml

- name: Get Infra Container(s)
  containers.podman.podman_pod_info:
    name: '{{ prometheus_hostname }}-0-pod'
  register: pod_info

- set_fact:
    prometheus_infra_id: '{{ pod_info.pods[0].InfraContainerID  }}'

- name: Get Infra Container info
  containers.podman.podman_container_info:
    name: '{{ prometheus_infra_id }}'
  register: container_info

- set_fact:
    prometheus_pod_ip: '{{ container_info | json_query(query) }}'
  vars:
    query: 'containers[0].NetworkSettings.Networks.{{ prometheus_podman_network }}.IPAddress'

- debug:
    msg: '{{ prometheus_hostname }}-0 pod IP: {{ prometheus_pod_ip }}'
