---
- name: Create Prometheus configuration directory
  file:
    path: '{{ prometheus_base_dir }}/{{ prometheus_hostname }}-config/'
    mode: '0775'
    state: directory

- name: Create pid file directory
  file:
    path: '{{ prometheus_base_dir }}/pids/'
    state: directory

- name: Create alerting rules directory
  file:
    path: '{{ prometheus_base_dir }}/{{ prometheus_hostname }}-config/rules/'
    mode: '0775'
    state: directory

- name: Copy rules files
  get_url:
    url: '{{ item.url }}'
    dest: '{{ prometheus_base_dir }}/{{ prometheus_hostname }}-config/rules/{{ item.name }}'
    mode: '0644'
  loop: '{{ prometheus_alerting_rules }}'
  when: prometheus_alerting_rules | length > 0
  notify:
    - Restart Prometheus 0
    - Restart Prometheus 1

- set_fact:
    prometheus_flags: '{{ prometheus_flags + [ item ] }}'
  loop:
    - --storage.tsdb.max-block-duration=2h
    - --storage.tsdb.min-block-duration=2h
    - --web.enable-admin-api
    - --web.enable-lifecycle
  when: prometheus_thanos_sidecar

- include_tasks: single-deploy.yml

- name: Get Prometheus 0 Pod Infra Container
  containers.podman.podman_pod_info:
    name: '{{ prometheus_hostname }}-0-pod'
  register: pod_info

- set_fact:
    prometheus_0_infra_id: '{{ pod_info.pods[0].InfraContainerID  }}'

- name: Get Infra Container info
  containers.podman.podman_container_info:
    name: '{{ prometheus_0_infra_id }}'
  register: container_info

- set_fact:
    prometheus_0_pod_ip: '{{ container_info | json_query(query) }}'
  vars:
    query: 'containers[0].NetworkSettings.Networks.{{ prometheus_podman_network }}.IPAddress'

- name: Deploy HA pair
  block:
  - include_tasks: ha-deploy.yml
    when: prometheus_ha_pair
  
  - name: Get Prometheus 1 Pod Infra Container
    containers.podman.podman_pod_info:
      name: '{{ prometheus_hostname }}-1-pod'
    register: pod_info
  
  - set_fact:
      prometheus_1_infra_id: '{{ pod_info.pods[0].InfraContainerID  }}'
  
  - name: Get Infra Container info
    containers.podman.podman_container_info:
      name: '{{ prometheus_1_infra_id }}'
    register: container_info
  
  - set_fact:
      prometheus_1_pod_ip: '{{ container_info | json_query(query) }}'
    vars:
      query: 'containers[0].NetworkSettings.Networks.{{ prometheus_podman_network }}.IPAddress'

  when: prometheus_ha_pair

- include_tasks: side-car.yml
  when: prometheus_thanos_sidecar

- debug:
    msg:
    - '{{ prometheus_hostname }}-0 pod IP: {{ prometheus_0_pod_ip }}'
  when: not prometheus_ha_pair

- debug:
    msg:
    - '{{ prometheus_hostname }}-0 pod IP: {{ prometheus_0_pod_ip }}'
    - '{{ prometheus_hostname }}-1 pod IP: {{ prometheus_1_pod_ip }}'
  when: prometheus_ha_pair
